jobs:
  build-sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: pytest tests/simulation
      - run: docker build -t registry/app/simulator:latest .
  deploy-sim:
    needs: build-sim
    runs-on: ubuntu-latest
    steps:
      - uses: dtzar/helm-kubectl@v1
      - run: helm upgrade --install digital-twin ./helm/digital-twin
