apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-exchange-rates
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fetcher
              image: registry.delivery.com/currency-service:latest
              command: ["node","dist/fetchRates.js"]
              env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: currency-secret
                      key: apiKey
                - name: REDIS_URL
                  value: redis://redis:6379/0
          restartPolicy: OnFailure
