apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
  labels:
    app: fluentd
    tier: logging
    environment: production
data:
  fluent.conf: |
    <source>
      @type              tail
      path               /var/log/containers/*.log
      pos_file           /var/log/fluentd-containers.log.pos
      tag                kube.*
      format             json
    </source>
    <match **>
      @type loki
      url "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      extract_kubernetes_labels true
    </match>
