apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic
            image: restic/restic:latest
            env:
              - name: RESTIC_REPOSITORY
                value: "s3:http://minio.delivery.svc:9000/restic"
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef: { name: restic-creds, key: accessKey }
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef: { name: restic-creds, key: secretKey }
            command: ["restic","backup","/data"]
            volumeMounts:
            - name: data
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: data-pvc
