apiVersion: apps/v1
kind: Deployment
metadata:
  name: segment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: segment-service
  template:
    metadata:
      labels:
        app: segment-service
    spec:
      containers:
        - name: segment-service
          image: registry.delivery.com/segment-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: HUBSPOT_API
              valueFrom:
                secretKeyRef:
                  name: marketing-secrets
                  key: hubspot_api
            - name: HUBSPOT_KEY
              valueFrom:
                secretKeyRef:
                  name: marketing-secrets
                  key: hubspot_key
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
