apiVersion: serving.kubeflow.org/v1
kind: InferenceService
metadata:
  name: personalization-model
spec:
  predictor:
    tensorflow:
      storageUri: "gs://models/personalization/1"
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
