import express from 'express';
import walletMetricsRouter from './routes/walletMetrics';
// ...existing code...
const app = express();
// ...existing code...
app.use('/api', walletMetricsRouter);
// ...existing code...
export default app;
