jobs:
  build-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t registry/app/edge-services:latest .
  deploy-edge:
    needs: build-edge
    runs-on: ubuntu-latest
    steps:
      - uses: dtzar/helm-kubectl@v1
      - run: helm upgrade --install edge-mec ./helm/edge-mec
