apiVersion: batch/v1
kind: Job
metadata:
  name: dsar-discovery-dag
spec:
  template:
    spec:
      containers:
      - name: dsar-discovery
        image: your-dsar-dags-image
        command: ["airflow", "dags", "trigger", "dsar_discovery"]
      restartPolicy: Never
