openapi: 3.0.0
info:
  title: Loyalty Integration API
  version: 1.0.0
paths:
  /loyalty/balance/{userId}:
    post:
      summary: Get loyalty balance for a user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Loyalty balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  balance:
                    type: number
