configuration:
  provider: aws
  backupStorageLocation:
    name: default
    objectStorage:
      bucket: delivery-velero-backups
      prefix: velero
  volumeSnapshotLocation:
    name: default
    config:
      region: eu-central-1
credentials:
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = ...
      aws_secret_access_key = ...
