apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata: { name: pod-delete }
spec:
  definition:
    scope: Namespaced
    permissions: [...]
    image: "litmuschaos/go-runner:latest"
    args: ["-name", "pod-delete", "-run"]
