apiVersion: chaosmesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-experiment
  namespace: delivery
spec:
  action: pod-kill
  mode: fixed-pod-count
  value: '1'
  selector:
    namespaces:
      - delivery
    labelSelectors:
      'app': 'order-service'
  duration: '30s'
