jobs:
  build-pq:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --branch oqs-OpenSSL https://github.com/open-quantum-safe/openssl.git
      - run: ./config && make && make install
      - run: docker build -t registry/pq-nginx:latest .
  deploy-pq:
    needs: build-pq
    runs-on: ubuntu-latest
    steps:
      - uses: dtzar/helm-kubectl@v1
      - run: helm upgrade --install pq-proxy ./helm/pq-proxy
