apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: delivery-root
spec:
  project: default
  source:
    repoURL: https://github.com/org/delivery-infra.git
    path: gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
