apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-workers
spec:
  replicas: 3
  selector:
    matchLabels: { app: celery-worker }
  template:
    metadata:
      labels: { app: celery-worker }
    spec:
      containers:
        - name: worker
          image: registry.delivery.com/celery-worker:latest
          env:
            - name: BROKER_URL
              value: redis://redis:6379/0
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-workers-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-workers
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
