apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower
spec:
  replicas: 1
  selector:
    matchLabels: { app: flower }
  template:
    metadata:
      labels: { app: flower }
    spec:
      containers:
        - name: flower
          image: mher/flower:0.9.7
          args: ["--broker=redis://redis:6379/0", "--port=5555"]
---
apiVersion: v1
kind: Service
metadata:
  name: flower
spec:
  type: ClusterIP
  ports:
    - port: 5555
  selector: { app: flower }
