jobs:
  test-biometric:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test
  deploy-biometric:
    needs: test-biometric
    runs-on: ubuntu-latest
    steps:
      - uses: dtzar/helm-kubectl@v1
      - run: helm upgrade --install biometric ./helm/biometric
