# KEDA ScaledObject example for order-service
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-service-scaledobject
spec:
  scaleTargetRef:
    name: order-service
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "60"
