apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaign-service
  template:
    metadata:
      labels:
        app: campaign-service
    spec:
      containers:
      - name: campaign-service
        image: your-campaign-service-image
        ports:
        - containerPort: 8080
