version: '3.8'
services:
  api:
    image: registry.delivery.com/api:sandbox
    ports: ['3001:3000']
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox
