name: serverless-deploy
on: [push]
jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build:lambda
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt && terraform validate
  deploy:
    needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform apply -auto-approve
