# Monitoring-Export für Segmentierungsservice (Prometheus)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: segment-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: segment-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
