apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: svc-rollout
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 60 }
        - setWeight: 50
        - pause: { duration: 60 }
      trafficRouting:
        istio: { virtualService: { name: svc, routes: [primary] } }
      autoRollback: true
