route:
  group_by: ['alertname','service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'oncall'
  routes:
    - match:
        severity: critical
      receiver: 'pagerduty'
      continue: false
receivers:
  - name: 'pagerduty'
    pagerduty_configs:
      - routing_key: '{{ .CommonAnnotations.pagerduty_key }}'
        severity: '{{ .CommonLabels.severity }}'
  - name: 'oncall'
    slack_configs:
      - channel: '#incidents'
        text: '{{ .CommonAnnotations.summary }}'
