global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'federate-aws'
    honor_labels: true
    metrics_path: '/federate'
    static_configs:
      - targets: ['prom-aws:9090']
  - job_name: 'federate-gcp'
    honor_labels: true
    metrics_path: '/federate'
    static_configs:
      - targets: ['prom-gcp:9090']
