groups:
  - name: post_launch
    rules:
      - alert: ServiceLatencyHigh
        expr: histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket[5m])) by (le, service)) > 1.0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "95th percentile latency for {{ $labels.service }} > threshold"
