apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-bot
  template:
    metadata:
      labels:
        app: whatsapp-bot
    spec:
      containers:
      - name: whatsapp
        image: your-whatsapp-image
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-bot
spec:
  selector:
    app: whatsapp-bot
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
