name: CI/CD Asset Server
on:
  push:
    paths:
      - 'asset-server/**'
    branches: [ main ]
jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      servicePath: 'asset-server'
      serviceName: 'asset-server'
