name: CI Accessibility
on: [pull_request, push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: ESLint A11y Check
        run: npm run lint
      - name: Run jest-axe
        run: npm test -- --runInBand a11y.test.tsx
      - name: Start Storybook & Pa11y
        run: |
          npx start-storybook -p 6006 &
          npx wait-on http://localhost:6006
          npx pa11y-ci --config pa11yci.json
