name: CI Blockchain Payment & Loyalty
on: [push]
jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install & Test Smart Contracts
        run: |
          npm ci
          npx hardhat compile
          npx hardhat test
      - name: Deploy Subgraph
        run: |
          npm install -g @graphprotocol/graph-cli
          graph auth $IPFS_HASH
          graph deploy --product hosted-service your/subgraph
      - name: Setup Python
        run: pip install fastapi gql pytest
      - name: Test Off-Chain API
        run: pytest tests
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to K8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/blockchain-payment-loyalty.yaml
