name: CI Currency Service
on: [push]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install & Test
        run: |
          npm ci
          npm run lint
          npm test
      - name: Build & Push Docker
        run: |
          docker build -t registry.delivery.com/currency-service:${{github.sha}} .
          docker push registry.delivery.com/currency-service:${{github.sha}}
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to K8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/currency-deployment.yaml
          kubectl apply -f k8s/currency-cronjob.yaml
