name: CI Federated Learning
on: [push]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        run: pip install fastapi tensorflow-federated prometheus-client pytest
      - name: Test Coordinator
        run: pytest app/tests/test_coordinator.py
      - name: Build & Push Docker
        run: |
          docker build -t registry.delivery.com/fedu-coordinator:${{github.sha}} .
          docker push registry.delivery.com/fedu-coordinator:${{github.sha}}
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to K8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/federated-learning.yaml
