name: CI Social Feed
on: [push]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install & Test Node
        run: |
          npm ci
          npm run lint
          npm test
      - name: Run i18n QA
        run: python ../../scripts/i18n-qa.py
      - name: Build & Push Docker
        run: |
          docker build -t registry.delivery.com/social-service:${{github.sha}} .
          docker push registry.delivery.com/social-service:${{github.sha}}
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to K8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/social-feed-deployment.yaml
