name: CI Segmentation
on: [push]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        run: pip install fastapi feast mlflow xgboost pytest
      - name: Run Tests
        run: pytest tests
      - name: Build Docker & Push
        run: |
          docker build -t registry.delivery.com/segment-service:${{github.sha}} .
          docker push registry.delivery.com/segment-service:${{github.sha}}
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to K8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/segmentation-deployment.yaml
      - name: Run i18n QA
        run: python ../../scripts/i18n-qa.py
