name: CI SEO Recommendations
on: [push]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        run: pip install fastapi openai pymongo pytest
      - name: Test Recommendation Service
        run: pytest app/tests
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install & Test Next.js Plugin
        run: |
          cd plugins
          npm ci
          npm test
      - name: Build & Push Services
        run: |
          docker build -t registry.delivery.com/seo-rec:${{github.sha}} -f app/Dockerfile app
          docker push registry.delivery.com/seo-rec:${{github.sha}}
          docker build -t registry.delivery.com/seo-plugin:${{github.sha}} -f plugins/Dockerfile plugins
          docker push registry.delivery.com/seo-plugin:${{github.sha}}
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to K8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/seo-rec-deployment.yaml
          kubectl apply -f k8s/seo-plugin-deployment.yaml
