name: CI Task Management
on: [push]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node & Python
        run: |
          npm ci
          pip install rq pytest
      - name: Test Node Tasks
        run: npm test --workspace=restaurant-service
      - name: Test Python Tasks
        run: pytest backend/restaurant-service/tasks/tests
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to K8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/task-deployment.yaml
