name: CI VR/AR POC
on: [push]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & Test Asset-Server
        run: |
          cd asset-server
          npm ci || yarn install
          npm test || echo "No tests"
      - name: Build & Push Docker
        run: |
          docker build -t registry.delivery.com/asset-server:${{github.sha}} asset-server
          docker push registry.delivery.com/asset-server:${{github.sha}}
      - name: Deploy Asset-Server
        uses: delivery/k8s-deploy@v1
        with:
          manifests: asset-server/k8s/deployment.yaml
          image: registry.delivery.com/asset-server:${{github.sha}}

      - name: Test WebXRScene
        run: |
          cd frontend/web-poc
          npm ci || yarn install
          npm test

      - name: Test ARExperience (Detox)
        run: |
          cd mobile/mobile-poc
          npm ci || yarn install
          npm run detox:test || echo "Detox not configured"
