name: CI Worker & Scheduler
on:
  push:
    paths:
      - 'worker/**'
      - 'worker/k8s/**'
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python & Test
        run: |
          pip install celery pytest prometheus_client
          pytest worker/tests
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: worker/k8s/deployment.yaml,worker/k8s/flower.yaml
