name: CI Zero Trust Security
on: [push]
jobs:
  security-policies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint OPA Policies
        run: |
          opa fmt -w policies
          opa test policies
      - name: Check NetworkPolicy Yaml
        run: kubeval k8s/networkpolicy.yaml
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to K8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/security-deployment.yaml
