on:
  push:
    paths:
      - 'backend/consent/consent.middleware.js'
jobs:
  deploy-consent:
    runs-on: ubuntu-latest
    steps:
      - uses: dtzar/helm-kubectl@v1
      - run: helm upgrade --install consent ./helm/consent
