name: CI DesignSystem

on: [push, pull_request]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install
        run: npm ci
      - name: Lint & Typecheck
        run: npm run lint && npm run build:types
      - name: Test Components
        run: npm test --workspaces
      - name: Storybook Build & Chromatic
        run: npm run storybook:build && npx chromatic --project-token=$CHROMATIC_TOKEN
      - name: Publish Package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public -w packages/ui-components
