name: Edge & Serverless CI/CD

jobs:
  test-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install and Test Worker
        run: |
          cd edge/worker
          npm install
          npm test

  deploy-edge:
    runs-on: ubuntu-latest
    needs: [test-edge]
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Init & Apply Edge
        working-directory: infra/edge
        run: |
          terraform init
          terraform apply -auto-approve

  test-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Test Lambda
        run: |
          cd serverless/lambda
          npm install
          npm test

  deploy-lambda:
    runs-on: ubuntu-latest
    needs: [test-lambda]
    steps:
      - uses: actions/checkout@v3
      - name: Build and Package Lambda
        run: |
          cd serverless/lambda
          npm run build
          zip -r package.zip .
      - name: Terraform Init & Apply Lambda
        working-directory: infra/edge
        run: |
          terraform init
          terraform apply -auto-approve
