on:
  push:
    paths:
      - 'backend/finops-anomaly/**'
jobs:
  build-anomaly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: pytest tests/ || exit 1
      - run: docker build -t registry/finops-anomaly:latest .
  deploy-anomaly:
    needs: build-anomaly
    runs-on: ubuntu-latest
    steps:
      - uses: dtzar/helm-kubectl@v1
      - run: helm upgrade --install finops-anomaly ./helm/finops-anomaly
