on:
  push:
    paths:
      - 'flux-system/**'
      - 'constrainttemplates/**'
      - 'constraints/**'
jobs:
  validate-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: helm repo add fluxcd https://charts.fluxcd.io
      - run: kustomize build ./flux-system
  deploy-flux:
    needs: validate-manifests
    runs-on: ubuntu-latest
    steps:
      - uses: azure/k8s-deploy@v1
        with:
          manifests: flux-system/*.yaml
  policy-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: opa test constrainttemplates/
  deploy-policies:
    needs: policy-lint
    runs-on: ubuntu-latest
    steps:
      - uses: azure/k8s-deploy@v1
        with:
          manifests: constrainttemplates/*.yaml,constraints/*.yaml
