on:
  push:
    paths:
      - 'terraform/slurm.tf'
jobs:
  build-batch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r batch/requirements.txt
      - run: pytest batch/tests
  deploy-hpc:
    needs: build-batch
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5
      - run: terraform init terraform/
      - run: terraform apply -auto-approve terraform/slurm.tf
