name: IaC Security Scan
on:
  pull_request:
    paths:
      - 'infra/**/*.tf'
      - 'infra/**/*.yaml'
      - 'charts/**'
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Checkov
        uses: bridgecrewio/checkov@v12
        with:
          directory: infra/terraform
          output_format: 'junitxml'
        continue-on-error: false
      - name: Upload Checkov Report
        uses: actions/upload-artifact@v3
        with:
          name: checkov-report
          path: checkov-report.xml

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Run tfsec
        run: tfsec infra/terraform

  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.33.0/conftest_0.33.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.33.0_Linux_x86_64.tar.gz -C /usr/local/bin conftest
      - name: Run Conftest
        run: |
          find infra/k8s -name '*.yaml' | xargs conftest test --policy policy/opa

  notify:
    needs: [checkov, tfsec, conftest]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ secrets.SLACK_IAC_CHANNEL }}
          slack-message: |
            :warning: *IaC Scan Failure*  
            Repository: `${{ github.repository }}`  
            Pull Request: `${{ github.event.pull_request.html_url }}`  
            Bitte prüfen Sie die Sicherheitsberichte.
