on:
  push:
    paths:
      - 'helm/jupyterhub-config.yaml'
jobs:
  deploy-jupyterhub:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/k8s-deploy@v1
        with:
          manifests: k8s/jupyterhub/*.yaml
