on:
  push:
    paths:
      - 'graph_api/**'
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: pytest --maxfail=1 --disable-warnings -q
  deploy:
    needs: build
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:latest
    steps:
      - run: helm upgrade --install knowledge-graph ./helm/knowledge-graph
