on: push:
  tags: ['v*.*.*']
jobs:
  sentry-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Sentry CLI
        run: npm install -g @sentry/cli
      - name: Create Sentry Release
        run: |
          export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-cli releases new ${{ github.ref_name }}
          sentry-cli releases set-commits --auto ${{ github.ref_name }}
          sentry-cli releases finalize ${{ github.ref_name }}
