name: CI/CD Restaurant Service
on:
  push:
    paths:
      - 'backend/restaurant-service/**'
    branches: [ main ]
jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      servicePath: 'backend/restaurant-service'
      serviceName: 'restaurant-service'
