name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Rollback to version (blue/green)'
        required: true
        default: 'blue'

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Rollback Service
        run: |
          kubectl set selector service/api-gateway app=api-gateway,version=${{ github.event.inputs.version }}
          kubectl rollout status deployment/api-gateway-${{ github.event.inputs.version }}
