name: SAST Analysis
on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.java'
      - '**/*.py'
  push:
    branches: [main]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectKey: delivery-platform
          organization: your-org
          scannerMode: CLI
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
