on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  test-sla:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: incidents
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Install & Test
        run: |
          pip install flask psycopg2 pypd pytest
          pytest tests/test_incident_service.py || true
