name: Test
on:
  workflow_call:
    inputs:
      servicePath:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: ${{ inputs.servicePath }}
        run: npm ci || yarn install
      - name: Run Linter
        working-directory: ${{ inputs.servicePath }}
        run: npm run lint || echo "No linter"
      - name: Run Adaptive UI Tests
        working-directory: ${{ inputs.servicePath }}
        run: npm test -- --testPathPattern=AdaptiveCard.test.tsx || echo "No AdaptiveCard tests"
      - name: Run Tests
        working-directory: ${{ inputs.servicePath }}
        run: npm test || yarn test || echo "No tests"
