openapi: 3.0.0
info:
  title: DSAR API
  version: 1.0.0
paths:
  /dsar:
    post:
      summary: Create DSAR request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subject_id:
                  type: string
                request_type:
                  type: string
      responses:
        '200':
          description: Request created
  /dsar/{subject_id}:
    get:
      summary: Get DSAR request status
      parameters:
        - in: path
          name: subject_id
          schema:
            type: string
      responses:
        '200':
          description: Status
