openapi: 3.0.0
info:
  title: Segmentation API
  version: 1.0.0
paths:
  /segment/{user_id}:
    get:
      summary: Get user segment and propensity
      parameters:
        - in: path
          name: user_id
          schema:
            type: string
      responses:
        '200':
          description: Segment and propensity
