apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-restore
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/org/delivery-infra.git
    path: disaster/velero-restore
  destination:
    server: https://kubernetes.default.svc
    namespace: recovery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
