openapi: 3.0.3
info:
  title: Delivery Platform API
  version: 1.0.0
servers:
  - url: https://api.delivery.com/v1
paths:
  /orders:
    get:
      summary: List orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        total:
          type: number
