apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistant-webhook
  template:
    metadata:
      labels:
        app: assistant-webhook
    spec:
      containers:
      - name: webhook
        image: your-webhook-image
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: assistant-webhook
spec:
  selector:
    app: assistant-webhook
  ports:
  - protocol: TCP
    port: 8500
    targetPort: 8500
