name: CI Subscriptions
on:
  push:
    paths:
      - 'subscription/**'
      - 'webhook.controller.ts'
      - 'subscription.module.ts'
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node & Stripe
        run: |
          npm ci
      - name: Test Subscription Service
        run: npm test --workspace=subscription
      - name: Build & Push Docker Image
        run: |
          docker build -t registry.delivery.com/subscription-service:${{github.sha}} subscription
          docker push registry.delivery.com/subscription-service:${{github.sha}}
      - name: Deploy to Kubernetes
        uses: delivery/k8s-deploy@v1
        with:
          manifests: k8s/subscription-deployment.yaml
